homepage/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'homepage'

urlpatterns = [
    url(r'^$', views.login_view, name="login"),
    url(r'^compose/$', views.compose_view, name="compose"),
    url(r'^inbox/$', views.inbox_view, name="inbox"),
    url(r'^sent/$', views.sent_view, name="sent"),
    url(r'^trash/$', views.trash_view, name="trash"),
    url(r'^options/$', views.options_view, name="options")
   
]

mysite/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/$', admin.site.urls),
    url(r'^',include('homepage.urls')),
    
]

homepage/models.py
from django.db import models

class UserDetails(models.Model):
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=50)

class option(models.Model):
    option = models.CharField(max_length=100)

class Details:
    email : str
    password : str

class Compose:
    recipient : str
    subject : str
    body : str

homepage/forms.py
from django import forms
from . import models

class UserForm(forms.ModelForm):
    class Meta:
        model = models.UserDetails
        fields = ['email','password']
        widgets = {
        'email' : forms.EmailInput(),
        'password': forms.PasswordInput(),
        }

homepage/views.py
from django.shortcuts import render, redirect
from . import forms
from .models import Details
from .models import Compose
import imaplib,email
from gtts import gTTS
import os
from playsound import playsound
from django.http import HttpResponse
import speech_recognition as sr
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from django.http import JsonResponse
import re

file = "good"
i="0"
passwrd = ""
addr = ""
item =""
subject = ""
body = ""
s = smtplib.SMTP('smtp.gmail.com', 587)
s.starttls()
imap_url = 'imap.gmail.com'
conn = imaplib.IMAP4_SSL(imap_url)
attachment_dir = 'C:/Users/Chacko/Desktop/'

def texttospeech(text, filename):
    filename = filename + '.mp3'
    flag = True
    while flag:
        try:
            tts = gTTS(text=text, lang='en', slow=False)
            tts.save(filename)
            flag = False
        except:
            print('Trying again')
    playsound(filename)
    os.remove(filename)
    return

def speechtotext(duration):
    global i, addr, passwrd
    r = sr.Recognizer()
    with sr.Microphone() as source:
        r.adjust_for_ambient_noise(source, duration=1)
        playsound('speak.mp3')
        audio = r.listen(source, phrase_time_limit=duration)
    try:
        response = r.recognize_google(audio)
    except:
        response = 'N'
    return response

def convert_special_char(text):
    temp=text
    special_chars = ['attherate','dot','underscore','dollar','hash','star','plus','minus','space','dash']
    for character in special_chars:
        while(True):
            pos=temp.find(character)
            if pos == -1:
                break
            else :
                if character == 'attherate':
                    temp=temp.replace('attherate','@')
                elif character == 'dot':
                    temp=temp.replace('dot','.')
                elif character == 'underscore':
                    temp=temp.replace('underscore','_')
                elif character == 'dollar':
                    temp=temp.replace('dollar','$')
                elif character == 'hash':
                    temp=temp.replace('hash','#')
                elif character == 'star':
                    temp=temp.replace('star','*')
                elif character == 'plus':
                    temp=temp.replace('plus','+')
                elif character == 'minus':
                    temp=temp.replace('minus','-')
                elif character == 'space':
                    temp = temp.replace('space', '')
                elif character == 'dash':
                    temp=temp.replace('dash','-')
    return temp



def login_view(request):
    global i, addr, passwrd 

    if request.method == 'POST':
        text1 = "Welcome to our Voice Based Email. Login with your email account in order to continue. "
        texttospeech(text1, file + i)
        i = i + str(1)

        flag = True
        while (flag):
            texttospeech("Enter your Email", file + i)
            i = i + str(1)
            addr = speechtotext(10)
            
            if addr != 'N':
                texttospeech("You meant " + addr + " say yes to confirm or no to enter again", file + i)
                i = i + str(1)
                say = speechtotext(3)
                if say == 'yes' or say == 'Yes':
                    flag = False
            else:
                texttospeech("could not understand what you meant:", file + i)
                i = i + str(1)
        addr = addr.strip()
        addr = addr.replace(' ', '')
        addr = addr.lower()
        addr = convert_special_char(addr)
        print(addr)
        request.email = addr

        flag = True
        while (flag):
            texttospeech("Enter your password", file + i)
            i = i + str(1)
            passwrd = speechtotext(10)
            
            if addr != 'N':
                texttospeech("You meant " + passwrd + " say yes to confirm or no to enter again", file + i)
                i = i + str(1)
                say = speechtotext(3)
                if say == 'yes' or say == 'Yes':
                    flag = False
            else:
                texttospeech("could not understand what you meant:", file + i)
                i = i + str(1)
        passwrd = passwrd.strip()
        passwrd = passwrd.replace(' ', '')
        passwrd = passwrd.lower()
        passwrd = convert_special_char(passwrd)
        print(passwrd)

        imap_url = 'imap.gmail.com'
        #passwrd = ''
        #addr = ''
        conn = imaplib.IMAP4_SSL(imap_url)
        try:
            conn.login(addr, passwrd)
            s.login(addr, passwrd)
            texttospeech("Congratulations. You have logged in successfully. You will now be redirected to the menu page.", file + i)
            i = i + str(1)
            return JsonResponse({'result' : 'success'})
        except:
            texttospeech("Invalid Login Details. Please try again.", file + i)
            i = i + str(1)
            return JsonResponse({'result': 'failure'})

    
    detail  = Details()
    detail.email = addr
    detail.password = passwrd
    return render(request, 'homepage/login.html', {'detail' : detail}) 

def options_view(request):
    global i, addr, passwrd
    if request.method == 'POST':
        flag = True
        texttospeech("You are logged into your account. What would you like to do ?", file + i)
        i = i + str(1)
        while(flag):
            texttospeech("To compose an email say compose. To open Inbox folder say Inbox. To open Sent folder say Sent. To open Trash folder say Trash. To Logout say Logout. Do you want me to repeat?", file + i)
            i = i + str(1)
            say = speechtotext(3)
            if say == 'No' or say == 'no':
                flag = False
        texttospeech("Enter your desired action", file + i)
        i = i + str(1)
        act = speechtotext(5)
        act = act.lower()
        if act == 'compose':
            return JsonResponse({'result' : 'compose'})
        elif act == 'inbox':
            return JsonResponse({'result' : 'inbox'})
        elif act == 'sent':
            return JsonResponse({'result' : 'sent'})
        elif act == 'trash':
            return JsonResponse({'result' : 'trash'})
        elif act == 'log out':
            addr = ""
            passwrd = ""
            texttospeech("You have been logged out of your account and now will be redirected back to the login page.",file + i)
            i = i + str(1)
            return JsonResponse({'result': 'logout'})
        else:
            texttospeech("Invalid action. Please try again.", file + i)
            i = i + str(1)
            return JsonResponse({'result': 'failure'})
    elif request.method == 'GET':
        return render(request, 'homepage/options.html')

def compose_view(request):
    global i, addr, passwrd, s, item, subject, body
    if request.method == 'POST':
        text1 = "You have reached the page where you can compose and send an email. "
        texttospeech(text1, file + i)
        i = i + str(1)
        flag = True
        flag1 = True
        fromaddr = addr
        toaddr = list()
        while flag1:
            while flag:
                texttospeech("enter receiver's email address:", file + i)
                i = i + str(1)
                to = ""
                to = speechtotext(15)
                if to != 'N':
                    
                    texttospeech("You meant " + to + " say yes to confirm or no to enter again", file + i)
                    i = i + str(1)
                    say = speechtotext(5)
                    if say == 'yes' or say == 'Yes':
                        toaddr.append(to)
                        flag = False
                else:
                    texttospeech("could not understand what you meant", file + i)
                    i = i + str(1)
            texttospeech("Do you want to enter more recipients ?  Say yes or no.", file + i)
            i = i + str(1)
            say1 = speechtotext(3)
            if say1 == 'No' or say1 == 'no':
                flag1 = False
            flag = True

        newtoaddr = list()
        for item in toaddr:
            item = item.strip()
            item = item.replace(' ', '')
            item = item.lower()
            item = convert_special_char(item)
            newtoaddr.append(item)
            print(item)

        msg = MIMEMultipart()
        msg['From'] = fromaddr
        msg['To'] = ",".join(newtoaddr)
        flag = True
        while (flag):
            texttospeech("enter subject", file + i)
            i = i + str(1)
            subject = speechtotext(10)
            if subject == 'N':
                texttospeech("could not understand what you meant", file + i)
                i = i + str(1)
            else:
                flag = False
        msg['Subject'] = subject
        flag = True
        while flag:
            texttospeech("enter body of the mail", file + i)
            i = i + str(1)
            body = speechtotext(20)
            if body == 'N':
                texttospeech("could not understand what you meant", file + i)
                i = i + str(1)
            else:
                flag = False

        msg.attach(MIMEText(body, 'plain'))
        texttospeech("any attachment? say yes or no", file + i)
        i = i + str(1)
        x = speechtotext(3)
        x = x.lower()
        if x == 'yes':
            texttospeech("Do you want to record an audio and send as an attachment?", file + i)
            i = i + str(1)
            say = speechtotext(2)
            say = say.lower()
            if say == 'yes':
                texttospeech("Enter filename.", file + i)
                i = i + str(1)
                filename = speechtotext(5)
                filename = filename.lower()
                filename = filename + '.mp3'
                filename = filename.replace(' ', '')

homepage/templates/homepage/compose.html
{% extends 'base_layout.html' %}

{% block content %}
<body onmousedown = "WhichButtonCompose(event)">
	<nav class="navbar navbar-dark navbar-expand-lg fixed-top bg-dark navbar-custom">
        <div class="container"><a class="navbar-brand" style="font-size:150%;">VOICE BASED EMAIL FOR THE BLIND</a>
            
        </div>
    </nav>
    <header class="masthead text-left text-white">
    <div class="masthead-content">
        <div class="container">
            <center>
            <h4 class="masthead-heading mb-0" style = "margin-top: -100px; font-size: 60px;color:black;">COMPOSE MAIL</h4>
            </center>
                
            <br>
	
		<h4 class="sent-notification"></h4>

		<form id="here"  >
			<script> 
				$(document).ready(function(){
				setInterval(function(){
					  $("#here").load(window.location.href + " #here" );
				}, 1000);
				});
				</script>
		
            {% csrf_token %}
			<b><label style="color:black;font-size:30px" >RECIEPIENT'S EMAIL ID : </label></b><br>
			<input id="email" type="text" style="width: 100%;height: 50px;border-radius:5px " placeholder="Enter Email" required value="{{compose.recipient}}">
			<br><br>

			<b><label style="color:black;font-size:30px" >SUBJECT : </label></b><br>
			<input id="subject" type="text" style="width: 100%;height: 50px;border-radius:5px " placeholder=" Enter Subject" required value="{{compose.subject}}"> 
			<br><br>

			<b><label style="color:black;font-size:30px" >BODY : </label></b><br>
			<input id="body" rows="5" style="width: 100%;height: 200px;border-radius:5px " placeholder="Type Message"required value="{{compose.body}}">
			<br>

            <center>
            <input href="#"class="btn btn-primary btn-xl rounded-pill mt-5" role="button" type="button" onclick="sendEmail()"value="SEND MAIL"style="background-color:black;"></a>
            </center>  
		</form>
        </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header>
<footer class="py-5 bg-black">
	<div class="container">
		<p class="text-center text-white m-0 small">Copyright&nbsp;© Voice Based Email&nbsp;</p>
	</div>
</footer>

<script>
	function WhichButtonCompose(event){
		$.ajax({
        url: "{% url 'homepage:compose' %}",
        method: 'POST',
        data: { 'csrfmiddlewaretoken': '{{ csrf_token }}'},
        success: function (data) {
			if(data.result == 'success'){
				window.location = "{% url 'homepage:options' %}";
			}
			else if(data.result == 'failure'){
				window.location = "{% url 'homepage:compose' %}";
			}
        }
    });
	}
</script>

{% endblock %}

homepage/templates/homepage/inbox.html
{% extends 'base_layout.html' %}

{% block content %}

	<body onmousedown = "SendPostRequestInbox(event)">
		<nav class="navbar navbar-dark navbar-expand-lg fixed-top bg-dark navbar-custom">
			<div class="container"><a class="navbar-brand" style="font-size:150%;">VOICE BASED EMAIL FOR THE BLIND</a>
				
			</div>
		</nav>
		<header class="masthead text-left text-white">
			<div class="masthead-content">
				<div class="container" >
					<center>
						<h4 class="masthead-heading mb-0" style = "margin-top: -100px; font-size: 60px;color:black;">INBOX PAGE</h4>			
						<br>
							<h2> What would you like to do? <h2><br>
					</center>
					
				<table align="center" >
					<tr>
						<td>
							
								<input href="compose.html"class="btn btn-primary btn-xl rounded-pill mt-5"
								class="button" role="button"
								style="width: 250px; background-color: black;" type="submit" 
								value="UNREAD"  style="background-color: black;">
						</td>
					</tr>
						
					<tr>
						<td>
							
								<input href="inbox.html"class="btn btn-primary btn-xl rounded-pill mt-5"
								 role="button"
								 style="width: 250px; background-color: black;" type="submit" 
								value="SEARCH" >
						</td>

					</tr>
						
					<tr>
						<td>
							
								<input href="options.html"class="btn btn-primary btn-xl rounded-pill mt-5" 
								role="button" 
								style="width: 250px; background-color: black;" type="submit"  
								value="BACK">
						</td>
					</tr>
						
					
					<tr>
						<td>
							
								<input href="login.html"class="btn btn-primary btn-xl rounded-pill mt-5"
								role="button"
								style="width: 250px; background-color: black;"  type="submit" 
								value="LOGOUT">
						</td>
					</tr>
						

				</table>
		
				</div>
			</div>
			<div class="bg-circle-1 bg-circle"></div>
			<div class="bg-circle-2 bg-circle"></div>
			<div class="bg-circle-3 bg-circle"></div>
			<div class="bg-circle-4 bg-circle"></div>
		</header>
		<footer class="py-5 bg-black">
			<div class="container">
				<p class="text-center text-white m-0 small">Copyright&nbsp;© Voice Based Email&nbsp;</p>
			</div>
		</footer>
	<script>
	function SendPostRequestInbox(event){
		$.ajax({
        url: "{% url 'homepage:inbox' %}",
        method: 'POST',
        data: { 'csrfmiddlewaretoken': '{{ csrf_token }}'},
        success: function (data) {
			if(data.result == 'success'){
				window.location = "{% url 'homepage:options' %}";
			}
			else if(data.result == 'logout'){
				window.location = "{% url 'homepage:login' %}";
			}
        }
    });
	}
	</script>

{% endblock %}

homepage/templates/homepage/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <body onmousedown = "SendPostRequestHome(event)" >
	
		<nav class="navbar navbar-dark navbar-expand-lg fixed-top bg-dark navbar-custom">
			<div class="container"><a class="navbar-brand" style="font-size:150%;">VOICE BASED EMAIL FOR THE BLIND</a>
				
			</div>
		</nav>
		<header class="masthead text-center text-white">
			<div class="masthead-content">
				<div class="container">
					<h1  style="margin-top:-60px; font-size:60px;color: black;" >LOGIN HERE</h1>
					
				<form action="homepage/login.html" method="POST">
					<br><br><br><br>
					<div class="container" >
						
						
						<div class="login" id = "here">
							<script> 
								$(document).ready(function(){
								setInterval(function(){
									  $("#here").load(window.location.href + " #here" );
								}, 1000);
								});
								</script>
							
							{% csrf_token %}
							  <h3 style="color: black;text-align: left;margin-left: 10%;">Email:</h3>
					
							<input type="text" placeholder="Email" name="email"required value={{detail.email}} >
					
							  <br><br>
							  <h3 style="color: black;text-align: left;margin-left: 10%;">Password: </h3>
							 <input type="password" placeholder="Password" name="password"required value={{detail.password}} >
					
							   <a href="options.html"> 
								<input href="options.html"class="btn btn-primary btn-xl rounded-pill mt-5" role="button" type="submit" value="LOGIN"style="background-color: black;"></a>
							  <br>
							  
							  
							</div>
						</div>							   
					</div>
				</div>
			</form>
				</div>
			</div>
			<div class="bg-circle-1 bg-circle"></div>
			<div class="bg-circle-2 bg-circle"></div>
			<div class="bg-circle-3 bg-circle"></div>
			<div class="bg-circle-4 bg-circle"></div>
		</header>

		<script>
		
			function SendPostRequestHome(event){
				
				$.ajax({
				url: "{% url 'homepage:login' %}",
				method: 'POST',
				data: { 'csrfmiddlewaretoken': '{{ csrf_token }}'},
				success: function (data) {
					
					if(data.result == 'success'){
						
						window.location = "{% url 'homepage:options' %}";
					}
					else if(data.result == 'failure'){
						window.location = "{% url 'homepage:login' %}";
					}
				}
			});
			}
			</script>
			
			<footer class="py-5 bg-black">
				<div class="container">
					<p class="text-center text-white m-0 small">Copyright&nbsp;© Voice Based Email&nbsp;</p>
				</div>
			</footer>


{% endblock %}

homepage/templates/homepage/options.html
{% extends 'base_layout.html' %}

{% block content %}

	<body onmousedown = "SendPostRequestOptions(event)">
		<nav class="navbar navbar-dark navbar-expand-lg fixed-top bg-dark navbar-custom">
			<div class="container"><a class="navbar-brand" style="font-size:150%;">VOICE BASED EMAIL FOR THE BLIND</a>
				
			</div>
		</nav>
		<header class="masthead text-left text-white">
			<div class="masthead-content">
				<div class="container" >
					<center>
						<h4 class="masthead-heading mb-0" style = "margin-top: -100px; font-size: 90px;color:black;">MENU PAGE</h4>			
						<br>
    
						<h2> What would you like to do? <h2><br>
						</center>
					
				<div container>
				<div class ="options">

				
				<table align="center" >
					<tr>
						<td>
							<a href="compose.html"> 
								<input href="compose.html"class="btn btn-primary btn-xl rounded-pill mt-5"
								class="button" role="button"
								style="width: 250px; background-color: black;" type="submit" 
								value="COMPOSE"  style="background-color: black;"></a>
						</td>
					</tr>
						
					<tr>
						<td>
							<a href="inbox.html"> 
								<input href="inbox.html"class="btn btn-primary btn-xl rounded-pill mt-5"
								 role="button"
								 style="width: 250px; background-color: black;" type="submit" 
								value="INBOX" ></a>
						</td>

					</tr>
						
					<tr>
						<td>
							<a href="sent.html"> 
								<input href="sent.html"class="btn btn-primary btn-xl rounded-pill mt-5" 
								role="button" 
								style="width: 250px; background-color: black;" type="submit"  
								value="SENT"></a>
						</td>
					</tr>
						
					<tr>
						<td>
							<a href="trash.html"> 
								<input href="trash.html"class="btn btn-primary btn-xl rounded-pill mt-5"
								role="button" 
								style="width: 250px; background-color: black;"  type="submit" 
								value="TRASH"></a>
						</td>
					</tr>
					<tr>
						<td>
							<a href="login.html"> 
								<input href="logout.html"class="btn btn-primary btn-xl rounded-pill mt-5"
								role="button"
								style="width: 250px; background-color: black;"  type="submit" 
								value="LOGOUT"></a>
						</td>
					</tr>
						

				</table>
			</div>
		</div>
						
		</div>
			</div>
			<div class="bg-circle-1 bg-circle"></div>
			<div class="bg-circle-2 bg-circle"></div>
			<div class="bg-circle-3 bg-circle"></div>
			<div class="bg-circle-4 bg-circle"></div>
		</header>
		<footer class="py-5 bg-black">
			<div class="container">
				<p class="text-center text-white m-0 small">Copyright&nbsp;© Voice Based Email&nbsp;</p>
			</div>
		</footer>
	<script>
	function SendPostRequestOptions(event){
		$.ajax({
        url: "{% url 'homepage:options' %}",
        method: 'POST',
        data: { 'csrfmiddlewaretoken': '{{ csrf_token }}'},
        success: function (data) {
			if(data.result == 'compose'){
				window.location = "{% url 'homepage:compose' %}";
			}
			else if(data.result == 'sent'){
				window.location = "{% url 'homepage:sent' %}";
			}	
			else if(data.result == 'inbox'){
				window.location = "{% url 'homepage:inbox' %}";
			}
			else if(data.result == 'trash'){
				window.location = "{% url 'homepage:trash' %}";
			}
			else if(data.result == 'logout'){
				window.location = "{% url 'homepage:login' %}";
			}
			else if(data.result == 'failure'){
				window.location = "{% url 'homepage:options' %}";
			}
        }
    });
	}
	</script>

{% endblock %}

homepage/templates/homepage/sent.html
{% extends 'base_layout.html' %}

{% block content %}
	<body onmousedown = "SendPostRequestSent(event)">
		<nav class="navbar navbar-dark navbar-expand-lg fixed-top bg-dark navbar-custom">
			<div class="container"><a class="navbar-brand" style="font-size:150%;">VOICE BASED EMAIL FOR THE BLIND</a>
				
			</div>
		</nav>
		<header class="masthead text-left text-white">
			<div class="masthead-content">
				<div class="container" >
					<center>
						<h4 class="masthead-heading mb-0" style = "margin-top: -100px; font-size: 60px;color:black;">SENT MAILS PAGE</h4>			
						<br>
						<h2> What would you like to do? <h2><br>
						
					</center>
					

				
				<table align="center" >
					<tr>
						<td>
							
								<input href="inbox.html"class="btn btn-primary btn-xl rounded-pill mt-5"
								 role="button"
								 style="width: 250px; background-color: black;" type="submit" 
								value="SEARCH" >
						</td>

					</tr>
						
					<tr>
						<td>
							
								<input href="options.html"class="btn btn-primary btn-xl rounded-pill mt-5" 
								role="button" 
								style="width: 250px; background-color: black;" type="submit"  
								value="BACK">
						</td>
					</tr>
						
					
					<tr>
						<td>
							
								<input href="login.html"class="btn btn-primary btn-xl rounded-pill mt-5"
								role="button"
								style="width: 250px; background-color: black;"  type="submit" 
								value="LOGOUT">
						</td>
					</tr>
						

				</table>
			
				</div>
			</div>
			<div class="bg-circle-1 bg-circle"></div>
			<div class="bg-circle-2 bg-circle"></div>
			<div class="bg-circle-3 bg-circle"></div>
			<div class="bg-circle-4 bg-circle"></div>
		</header>
		<footer class="py-5 bg-black">
			<div class="container">
				<p class="text-center text-white m-0 small">Copyright&nbsp;© Voice Based Email&nbsp;</p>
			</div>
		</footer>
	<script>
	function SendPostRequestSent(event){
		$.ajax({
        url: "{% url 'homepage:sent' %}",
        method: 'POST',
        data: { 'csrfmiddlewaretoken': '{{ csrf_token }}'},
        success: function (data) {
			if(data.result == 'success'){
				window.location = "{% url 'homepage:options' %}";
			}
			else if(data.result == 'logout'){
				window.location = "{% url 'homepage:login' %}";
			}
        }
    });
	}
	</script>

{% endblock %}

homepage/templates/homepage/trash.html
{% extends 'base_layout.html' %}

{% block content %}
	<body onmousedown = "SendPostRequestTrash(event)">
		<nav class="navbar navbar-dark navbar-expand-lg fixed-top bg-dark navbar-custom">
			<div class="container"><a class="navbar-brand" style="font-size:150%;">VOICE BASED EMAIL FOR THE BLIND</a>
				
			</div>
		</nav>
		<header class="masthead text-left text-white">
			<div class="masthead-content">
				<div class="container" >
				<center>
					<h4 class="masthead-heading mb-0" style = "margin-top: -100px; font-size: 60px;color:black;">TRASH FOLDER</h4>			
						<br>
						<h2> What would you like to do? <h2><br>
					
				</center>
				
				<table align="center" >
				<tr>
						<td>
							
								<input href="inbox.html"class="btn btn-primary btn-xl rounded-pill mt-5"
								 role="button"
								 style="width: 250px; background-color: black;" type="submit" 
								value="SEARCH" >
						</td>

					</tr>
						
					<tr>
						<td>
							
								<input href="options.html"class="btn btn-primary btn-xl rounded-pill mt-5" 
								role="button" 
								style="width: 250px; background-color: black;" type="submit"  
								value="BACK">
						</td>
					</tr>
						
					
					<tr>
						<td>
							
								<input href="login.html"class="btn btn-primary btn-xl rounded-pill mt-5"
								role="button"
								style="width: 250px; background-color: black;"  type="submit" 
								value="LOGOUT">
						</td>
					</tr>
						

				</table>
			
				</div>
			</div>
			<div class="bg-circle-1 bg-circle"></div>
			<div class="bg-circle-2 bg-circle"></div>
			<div class="bg-circle-3 bg-circle"></div>
			<div class="bg-circle-4 bg-circle"></div>
		</header>
		<footer class="py-5 bg-black">
			<div class="container">
				<p class="text-center text-white m-0 small">Copyright&nbsp;© Voice Based Email&nbsp;</p>
			</div>
		</footer>
	<script>
	function SendPostRequestTrash(event){
		$.ajax({
        url: "{% url 'homepage:trash' %}",
        method: 'POST',
        data: { 'csrfmiddlewaretoken': '{{ csrf_token }}'},
        success: function (data) {
			if(data.result == 'success'){
				window.location = "{% url 'homepage:options' %}";
			}
			else if(data.result == 'logout'){
				window.location = "{% url 'homepage:login' %}";
			}
        }
    });
	}
	</script>

{% endblock %}